### ISSUE TITLE
File storage as folder in laravel storage

### ISSUE THREAD

**Issue by mr-ben-jeckson** [thecodeholic/laravel-vue-ecommerce#4]
<img width="527" alt="issue" src="https://user-images.githubusercontent.com/30015653/204965954-2a64eab0-314f-46ac-9315-0f3099c84e5f.PNG">
i got an issue in development. file didn't go to storage as an image. It went as a folder

**Comment by mandixx** [comment]
That is correct, if you go into storage/app/public/images you will find there are folders in which you actually can see the images you aploaded.
Also its necessary to have folders since it will be a lot easier to upload multiple Images on the same product because then you will just have to retrieve the folder for each product and you will get all the images for it.

**Comment by dskanth** [comment]
Yes, facing the same issue.. the uploaded image goes go some path like:

![image](https://user-images.githubusercontent.com/1648228/227896967-711fe71f-447a-4c39-91a5-34a13a795ba3.png)

**Comment by mr-ben-jeckson** [comment]
@dskanth php artisan storage:link (Make sure you project still exists in NFTS storage). I had this issue because I created my project on external hard disk
